<div class="cleared"></div>
<div class="art-footer">
    <div class="art-footer-t"></div>
    <div class="art-footer-l"></div>
    <div class="art-footer-b"></div>
    <div class="art-footer-r"></div>
    <div class="art-footer-body">
        <a href="#" class="art-rss-tag-icon" title="RSS"></a>
        <div class="art-footer-text">
            <p>Copyright © 2012. All Rights Reserved.</p>
        </div>
        <div class="cleared"></div>
    </div>
</div>
<div class="cleared"></div>
</div>
</div>
<div class="cleared"></div>

</div>
</div>
</div>