<div id="art-page-background-glare">
    <div id="art-page-background-glare-image">
        <div id="art-main">
            <div class="art-sheet">
                <div class="art-sheet-tl"></div>
                <div class="art-sheet-tr"></div>
                <div class="art-sheet-bl"></div>
                <div class="art-sheet-br"></div>
                <div class="art-sheet-tc"></div>
                <div class="art-sheet-bc"></div>
                <div class="art-sheet-cl"></div>
                <div class="art-sheet-cr"></div>
                <div class="art-sheet-cc"></div>
                <div class="art-sheet-body">
                    <div class="art-header" style="display:none;">
                        <div class="art-header-center">
                            <div class="art-header-png"></div>
                            <div class="art-header-jpeg"></div>
                        </div>
                        <div class="art-logo">
                            <h1 id="name-text" class="art-logo-name"><a href="#">Фенечки</a></h1>
                            <h2 id="slogan-text" class="art-logo-text">Создай свою</h2>
                        </div>
                    </div>