<div class="art-layout-cell art-sidebar1">
    <div class="art-vmenublock">
        <div class="art-vmenublock-body">
            <div class="art-vmenublockheader">
                <h3 class="t">Меню</h3>
            </div>
            <div class="art-vmenublockcontent">
                <div class="art-vmenublockcontent-body">
                    <?php echo $this->menu; ?>
<!--                    <ul class="art-vmenu">
                        <li>
                            <a href="page.html?i1"><span class="l"></span><span class="r"></span><span class="t">Home</span></a>
                        </li>
                        <li>
                            <a href="page.html?i2"><span class="l"></span><span class="r"></span><span class="t">News</span></a>
                            <ul>
                                <li><a href="page.html?">Top 10</a></li>
                            </ul>
                        </li>

                    </ul>-->

                    <div class="cleared"></div>
                </div>
            </div>
            <div class="cleared"></div>
        </div>
    </div>

    <div class="cleared"></div>
</div>